using DynamicExpressions
import HerbCore
using HerbGrammar

function dynexpr_test()
    g = @cfgrammar begin
        Number = 1.0
        Number = x
        Number = Number + Number
        Number = Number * Number
    end


    operators = OperatorEnum(2 => (+, *))


    # Manually written function for the grammar above in a similar style to the one generated by make_interpreter
    function rulenode2dynexpr(rn::RuleNode)::Node{Float64}
        rule = HerbCore.get_rule(rn)
        children = HerbCore.get_children(rn)

        # Number = 1.0 => node with constant value 1.0
        rule == 1 && return Node{Float64}(; val=1.0)
        # Number = x => node with feature 1
        rule == 2 && return Node{Float64}(; feature=1)
        # Number = Number + Number => node with operator 1 and two children
        rule == 3 && return Node{Float64}(; op=1, children=(rulenode2dynexpr(children[1]), rulenode2dynexpr(children[2])))
        # Number = Number * Number => node with operator 2 and two children
        rule == 4 && return Node{Float64}(; op=2, children=(rulenode2dynexpr(children[1]), rulenode2dynexpr(children[2])))
        error("No matching rule index: ", rule)
    end

    prog = HerbCore.@rulenode(4{2,3{2,1}})  # x * (x + 1.0)
    dynexpr = rulenode2dynexpr(prog)

    expr = Expression(dynexpr; operators=operators, variable_names=["x"])

    # We can batch the evaluation of the expression on multiple inputs
    # DynamicExpressions are very fast for evaluating the same expression on many different inputs
    X = Float64[1.0 2.0 3.0]

    results = expr(X)  # evaluates x * (x + 1) for each x in X

    @assert results == [2.0, 6.0, 12.0]

    results
end

dynexpr_test()